checks:
    java:
        code_rating: true

build:
    environment:
        java: 'java-8-oracle'


#build:
#    tests:
#        override:
#            -
#                command: mvn clean package
#                coverage:
#                    file: 'scrutinizer-reports'
#                    format: 'jacoco'