checks:
    java:
        code_rating: true

build:
    environment:
        java: 'java-8-oracle'
    tests:
            override:
                -
                    command: mvn clean package
                    coverage:
                        file: '/cover'
                        format: 'jacoco'

#build:
#    tests:
#        override:
#            -
#                command: mvn clean package
#                coverage:
#                    file: 'scrutinizer-reports'
#                    format: 'jacoco'